// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtx6b_ygcGTecELZQT5lRCL9gX7X_7diw',
    appId: '1:433659289848:web:0fd4efaabdf8ad63af1b0d',
    messagingSenderId: '433659289848',
    projectId: 'attendance-33838',
    authDomain: 'attendance-33838.firebaseapp.com',
    storageBucket: 'attendance-33838.firebasestorage.app',
    measurementId: 'G-1BD1521F8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYXXcAhYLVdICkEk3qAtxEz_k3i3Liwoc',
    appId: '1:433659289848:android:6341e042e6c83862af1b0d',
    messagingSenderId: '433659289848',
    projectId: 'attendance-33838',
    storageBucket: 'attendance-33838.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdEpY4Nq5XNh8LnQH1XhHoOI2I4tRFxes',
    appId: '1:433659289848:ios:57a55b0a3bbe9226af1b0d',
    messagingSenderId: '433659289848',
    projectId: 'attendance-33838',
    storageBucket: 'attendance-33838.firebasestorage.app',
    iosBundleId: 'com.example.attendance',
  );
}
